#header()

${helper.getImports($robot, "RobotMap")}
from wpilib import LiveWindow

class RobotMap:
    """The RobotMap is a mapping from the ports sensors and actuators are wired
    into to a variable name. This provides flexibility changing wiring, makes
    checking the wiring easier and significantly reduces the number of magic
    numbers floating around."""

    @classmethod
    def Init(self):
#@autogenerated_code("constructors", "        ")
#parse("${exporter-path}core/robot_map-constructors.py")
#end

