#header()

#set($subsystem = $helper.getByName($subsystem-name, $robot))

from core import RobotMap
from commands import *
${helper.getImports($subsystem, "RobotMap")}
from wpilib import Subsystem

class #class($subsystem.name)(Subsystem):
    def __init__(self):
        super().__init__()
#@autogenerated_code("declarations", "        ")
#parse("${exporter-path}subsystems/Subsystem-declarations.py")
#end

    # Put methods for controlling this subsystem
    # here. Call these from Commands.

    def InitDefaultCommand(self):
#@autogenerated_code("default_command", "        ")
#parse("${exporter-path}subsystems/Subsystem-default_command.py")
#end

        # Set the default command for a subsystem here.
        # self.SetDefaultCommand(MySpecialCommand())

