#header()

#set($command = $helper.getByName($command-name, $robot))

from wpilib import Command
from robot import Robot

class #class($command.name)(Command):
    def __init__(self):
        super().__init__()
        # Use Requires() here to declare subsystem dependencies
        # eg. self.Requires(chassis)

#@autogenerated_code("requires", "        ")
#parse("${exporter-path}commands/Command-requires.py")
#end

    def Initialize(self):
        """Called just before this Command runs the first time"""
        pass

    def Execute(self):
        """Called repeatedly when this Command is scheduled to run"""
        pass

    def IsFinished(self):
        """Make this return true when this Command no longer needs to run
        Execute()"""
        return False

    def End(self):
        """Called once after IsFinished returns true"""
        pass

    def Interrupted(self):
        """Called when another command which requires one or more of the same
        subsystems is scheduled to run"""
        pass
