#header()

#set($command = $helper.getByName($command-name, $robot))

from wpilib import Command
from core import Robot

class #class($command.name)(Command):
    def __init__(self):
        super().__init__()
#@autogenerated_code("requires", "        ")
#parse("${exporter-path}commands/Command-requires.py")
#end

    # Called just before this Command runs the first time
    def Initialize(self):
#@autogenerated_code("Initialize", "        ")
#parse("${exporter-path}commands/SetpointCommand-Initialize.py")
#end

    # Called repeatedly when this Command is scheduled to run
    def Execute(self):
        pass

    # Make this return true when this Command no longer needs to run execute()
    def IsFinished(self):
#@autogenerated_code("IsFinished", "        ")
#parse("${exporter-path}commands/SetpointCommand-IsFinished.py")
#end

    # Called once after isFinished returns true
    def End(self):
        pass

    # Called when another command which requires one or more of the same
    # subsystems is scheduled to run
    def Interrupted(self):
        pass
